export const products = [
  // Tech Products
  {
    id: 1,
    name: "Canon Camera EOS 2000, Black 10x zoom",
    price: "998.00",
    originalPrice: "1128.00",
    image: "/assets/Image/tech/image 33.png",
    category: "Tech",
    rating: 4.5,
    reviews: 32,
    stock: 'In stock',
    brand: 'Canon',
    sku: 'CN-2000',
    description: 'High-quality DSLR camera with 10x optical zoom and advanced image processing for professional-grade photography.',
    images: [
      '/assets/Image/tech/image 33.png',
      '/assets/Image/tech/image 34.png',
      '/assets/Image/tech/6.png',
      '/assets/Image/tech/8.png',
      '/assets/Image/tech/image 86.png',
    ],
    specs: [
      { label: 'Type', value: 'DSLR' },
      { label: 'Zoom', value: '10x Optical' },
      { label: 'Color', value: 'Black' },
      { label: 'Warranty', value: '1 Year' },
    ]
  },
  {
    id: 2,
    name: "GoPro HERO6 4K Action Camera - Black",
    price: "799.00",
    image: "/assets/Image/tech/6.png",
    category: "Tech",
    rating: 4.8,
    reviews: 45,
    stock: 'In stock',
    brand: 'GoPro',
    sku: 'GP-H6',
    description: 'The ultimate action camera, capable of 4K video recording, waterproof design, and rugged durability for all your adventures.',
    images: [
      '/assets/Image/tech/6.png',
      '/assets/Image/tech/8.png',
      '/assets/Image/tech/image 86.png',
      '/assets/Image/tech/image 33.png',
      '/assets/Image/tech/image 34.png',
    ],
    specs: [
      { label: 'Resolution', value: '4K' },
      { label: 'Waterproof', value: 'Yes' },
      { label: 'Color', value: 'Black' },
      { label: 'Stabilization', value: 'Electronic' },
    ]
  },
  {
    id: 3,
    name: "Premium Wireless Headphones",
    price: "299.00",
    originalPrice: "399.00",
    image: "/assets/Image/tech/image 86.png",
    category: "Tech",
    rating: 4.7,
    reviews: 89,
    stock: 'In stock',
    brand: 'SoundPro',
    sku: 'SP-WH1',
    description: 'Experience crystal clear sound with active noise cancellation and 40-hour battery life.',
    images: [
      '/assets/Image/tech/image 86.png',
      '/assets/Image/tech/image 33.png',
      '/assets/Image/tech/image 34.png',
      '/assets/Image/tech/6.png',
      '/assets/Image/tech/8.png',
    ],
    specs: [
      { label: 'Type', value: 'Over-ear' },
      { label: 'Connectivity', value: 'Bluetooth 5.0' },
      { label: 'Noise Cancellation', value: 'Active' },
      { label: 'Battery Life', value: '40 Hours' },
    ]
  },
  {
    id: 4,
    name: "Smart Watch Pro Series",
    price: "199.00",
    image: "/assets/Image/tech/8.png",
    category: "Tech",
    rating: 4.6,
    reviews: 120,
    stock: 'In stock',
    brand: 'WatchMe',
    sku: 'WM-S1',
    description: 'Track your health and stay connected with this sleek and powerful smartwatch.',
    images: [
      '/assets/Image/tech/8.png',
      '/assets/Image/tech/image 86.png',
      '/assets/Image/tech/image 33.png',
      '/assets/Image/tech/image 34.png',
      '/assets/Image/tech/6.png',
    ],
    specs: [
      { label: 'Display', value: 'OLED' },
      { label: 'Heart Rate', value: 'Yes' },
      { label: 'GPS', value: 'Yes' },
      { label: 'Water Resistant', value: '50m' },
    ]
  },
  {
    id: 5,
    name: "Modern Laptop Stand Aluminum",
    price: "45.00",
    image: "/assets/Image/tech/image 34.png",
    category: "Tech",
    rating: 4.4,
    reviews: 25,
    stock: 'In stock',
    brand: 'DeskEase',
    sku: 'DE-LS',
    description: 'Ergonomic aluminum stand for laptops, improving posture and cooling efficiency.',
    images: [
      '/assets/Image/tech/image 34.png',
      '/assets/Image/tech/6.png',
      '/assets/Image/tech/8.png',
      '/assets/Image/tech/image 86.png',
      '/assets/Image/tech/image 33.png',
    ],
    specs: [
      { label: 'Material', value: 'Aluminum' },
      { label: 'Foldable', value: 'Yes' },
      { label: 'Compatibility', value: '11-17 inch' },
    ]
  },

  // Clothing Products
  {
    id: 11,
    name: "Mens Long Sleeve T-shirt Cotton",
    price: "75.00",
    originalPrice: "98.00",
    image: "/assets/Layout/alibaba/Image/cloth/image 24.png",
    category: "Clothing",
    rating: 4.5,
    reviews: 32,
    stock: 'In stock',
    brand: 'Customized',
    sku: 'CASUAL-001',
    description: 'Comfortable and stylish long sleeve t-shirt made from 100% organic cotton.',
    images: [
      '/assets/Layout/alibaba/Image/cloth/image 24.png',
      '/assets/Layout/alibaba/Image/cloth/2 1.png',
      '/assets/Layout/alibaba/Image/cloth/image 30.png',
      '/assets/Layout/alibaba/Image/cloth/Bitmap.png',
      '/assets/Layout/alibaba/Image/cloth/Bitmap (2).png',
    ],
    specs: [
      { label: 'Material', value: '100% Cotton' },
      { label: 'Fit', value: 'Slim Muscle' },
      { label: 'Style', value: 'Casual' },
    ]
  },
  {
    id: 12,
    name: "Jeans shorts for men blue color",
    price: "10.30",
    image: "/assets/Layout/alibaba/Image/cloth/2 1.png",
    category: "Clothing",
    rating: 4.3,
    reviews: 18,
    stock: 'In stock',
    brand: 'DenimCo',
    sku: 'DNM-SH01',
    description: 'Classic blue denim shorts for men, perfect for summer outings.',
    images: [
      '/assets/Layout/alibaba/Image/cloth/2 1.png',
      '/assets/Layout/alibaba/Image/cloth/image 24.png',
      '/assets/Layout/alibaba/Image/cloth/image 30.png',
      '/assets/Layout/alibaba/Image/cloth/Bitmap.png',
      '/assets/Layout/alibaba/Image/cloth/Bitmap (2).png',
    ],
    specs: [
      { label: 'Fabric', value: 'Denim' },
      { label: 'Color', value: 'Blue' },
      { label: 'Closure', value: 'Button' },
    ]
  },
  {
    id: 13,
    name: "Brown winter coat medium size",
    price: "12.50",
    image: "/assets/Layout/alibaba/Image/cloth/image 30.png",
    category: "Clothing",
    rating: 4.6,
    reviews: 54,
    stock: 'In stock',
    brand: 'Warmth',
    sku: 'WNT-CT01',
    description: 'Stay warm and stylish this winter with our premium brown coat.',
    images: [
      '/assets/Layout/alibaba/Image/cloth/image 30.png',
      '/assets/Layout/alibaba/Image/cloth/image 24.png',
      '/assets/Layout/alibaba/Image/cloth/2 1.png',
      '/assets/Layout/alibaba/Image/cloth/Bitmap.png',
      '/assets/Layout/alibaba/Image/cloth/Bitmap (2).png',
    ],
    specs: [
      { label: 'Season', value: 'Winter' },
      { label: 'Color', value: 'Brown' },
      { label: 'Material', value: 'Wool Blend' },
    ]
  },
]

export const categories = [
  {
    id: 1,
    name: "Tech",
    description: "Latest gadgets and electronics",
    image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=500&q=80",
  },
  {
    id: 2,
    name: "Interior",
    description: "Home decor and furniture",
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=500&q=80",
  },
  {
    id: 3,
    name: "Clothing",
    description: "Fashion and accessories",
    image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=500&q=80",
  },
]
